image: node:lts

variables:
  GIT_CLEAN_FLAGS: -ffd -e .npm -e .dpl -e .cache

stages:
  - test
  - deploy
  - clean

.rule_default_branch:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH
      when: always
    - when: never

.cache_npm:
  cache:
    key: npm-$CI_COMMIT_REF_SLUG
    paths:
      - .npm
      - node_modules

.install_doppler:
  script:
    - apt update && apt install -y curl gnupg
    - curl -Ls --tlsv1.2 --proto "=https" --retry 3 https://cli.doppler.com/install.sh | sh

.notif:
  script:
    - '[ ! -z "$NOTIF_MSG" ] && curl -X POST -d "{\"content\": \"${NOTIF_MSG}\"}" -H "Content-Type: application/json" $DISCORD_URL || echo "No message to send"'
    - '[ ! -z "$NOTIF_MSG" ] && curl -X POST -d "{\"text\": \"${NOTIF_MSG}\"}" -H "Content-Type: application/json" $SLACK_URL || echo "No message to send"'
