name: Deploy Extension
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install NPM packages
        uses: ./ci/github/install-npm
        with:
          app-dir: "apps-frontend/extension"

      - name: Build
        run: |
          cd apps-frontend/extension
          npm run build -- --verbose
          npm run package

      - name: Publish
        uses: PlasmoHQ/bpp@v3
        with:
          keys: ${{ secrets.BBP_KEYS }}
          artifact: apps-frontend/extension/build/chrome-mv3-prod.zip
