name: Doctor

on:
  schedule:
    - cron: "0 6 * * *"
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  doctor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install NPM packages
        uses: ./ci/github/install-npm

      - name: Build
        run: npm run build

      - name: Run doctor
        run: npm run doctor
