name: Doctor

on:
  schedule:
    - cron: "0 6 * * *"
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  doctor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache ~/.npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: v1-npm-${{ hashFiles('package-lock.json') }}

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: v1-node-modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: npm ci --cache ~/.npm --prefer-offline --no-audit --no-progress --legacy-peer-deps

      - name: Run doctor
        run: npm run doctor
